export const types = {
    PRELOADER_ON: 'PRELOADER_ON',
    PRELOADER_OFF: 'PRELOADER_OFF',

    ALERT_ON: 'ALERT_ON',
    ALERT_OFF: 'ALERT_OFF',

    ADD_USER: "ADD_USER",
    CLEAR_USERS: "CLEAR_USERS"
}